<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="metamodelSFrameweb" nsURI="https://github.com/danilloricardo/metamodel-sframeweb"
    nsPrefix="metamodelSFrameweb">
  <eClassifiers xsi:type="ecore:EClass" name="MappedClass" eSuperTypes="#//DomainClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="PersistentClass" eSuperTypes="#//DomainClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Table" eType="#//DomainTableName"
        eOpposite="#//DomainTableName/PersistentClassName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransientClass" eSuperTypes="#//DomainClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="SFrameweb">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Compose" lowerBound="1"
        upperBound="-1" eType="#//SFrameWebModel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Uses" lowerBound="1" upperBound="-1"
        eType="#//Framework" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SFrameWebModel" abstract="true" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Indite" lowerBound="1"
        eType="#//NamingMethod" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Framework" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package">
    <eStructuralFeatures xsi:type="ecore:EReference" name="FrameworkTagLib" lowerBound="1"
        eType="#//TagLib" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FrameworkRule" upperBound="-1"
        eType="#//Rule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FrameworkAnotation" lowerBound="1"
        upperBound="-1" eType="#//Anotation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="frameworkCategory" eType="#//FrameworkCategoryList"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainOntology" eSuperTypes="#//SFrameWebModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainUMLPackage" lowerBound="1"
        upperBound="-1" eType="#//DomainPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainUMLAssociation" upperBound="-1"
        eType="#//DomainAssociation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationModel" eSuperTypes="#//SFrameWebModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="NavigationUMLDependency"
        upperBound="-1" eType="#//NavigationDependency" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ViewUMLPackage" lowerBound="1"
        upperBound="-1" eType="#//ViewPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ControllerUMLPackage" lowerBound="1"
        upperBound="-1" eType="#//ControllerPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="NavigationUMLComposition"
        upperBound="-1" eType="#//NavigationComposition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationModel" eSuperTypes="#//SFrameWebModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ServiceUMLAssociation"
        lowerBound="1" upperBound="-1" eType="#//ServiceAssociation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ApplicationUMLPackage"
        lowerBound="1" upperBound="-1" eType="#//ApplicationPackage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersistenceModel" eSuperTypes="#//SFrameWebModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="PersistenceUMLPackage"
        lowerBound="1" upperBound="-1" eType="#//PersistencePackage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainAssociation" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Association">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collection" eType="#//Collection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="order" eType="#//Order"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cascade" eType="#//Cascade"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fetch" eType="#//Fetch"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SourceClass" lowerBound="1"
        eType="#//DomainClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TargetClass" lowerBound="1"
        eType="#//DomainClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainAttribute" abstract="true" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNull" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPersistent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Column" eType="#//DomainColumnName"
        eOpposite="#//DomainColumnName/DomainAttributeName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VersionAttribute" eSuperTypes="#//DomainAttribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="IdAttribute" eSuperTypes="#//DomainAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generation" eType="#//Generation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LOBAttribute" eSuperTypes="#//DomainAttribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="EmbeddedAttribute" eSuperTypes="#//DomainAttribute"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DateTimePrecision">
    <eLiterals name="timestamp"/>
    <eLiterals name="time" value="1"/>
    <eLiterals name="date" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Generation">
    <eLiterals name="auto"/>
    <eLiterals name="identity" value="1"/>
    <eLiterals name="sequence" value="2"/>
    <eLiterals name="none" value="3"/>
    <eLiterals name="table" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DecimalAttribute" eSuperTypes="#//DomainAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decimalPrecision" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decimalScale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateTimeAttribute" eSuperTypes="#//DomainAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateTimePrecision" eType="#//DateTimePrecision"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Collection">
    <eLiterals name="set"/>
    <eLiterals name="bag" value="1"/>
    <eLiterals name="list" value="2"/>
    <eLiterals name="map" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Order">
    <eLiterals name="natural"/>
    <eLiterals name="columnNameAsc" value="1"/>
    <eLiterals name="columnNameDesc" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Cascade">
    <eLiterals name="remove"/>
    <eLiterals name="merge" value="1"/>
    <eLiterals name="refresh" value="2"/>
    <eLiterals name="persist" value="3"/>
    <eLiterals name="none" value="4"/>
    <eLiterals name="all" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Fetch">
    <eLiterals name="eager"/>
    <eLiterals name="lazy" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Page" eSuperTypes="#//NavigationClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="PageClassAttribute" upperBound="-1"
        eType="#//UserViewAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PageTagLib" lowerBound="1"
        upperBound="-1" eType="#//Tag" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Mention" lowerBound="1"
        upperBound="-1" eType="#//TagLib"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Template" eSuperTypes="#//NavigationClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="TemplateClassAttribute"
        upperBound="-1" eType="#//UserViewAttribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Form" instanceTypeName="Tag" eSuperTypes="#//NavigationClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="FormClassAttribute" upperBound="-1"
        eType="#//FormComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Binary" eSuperTypes="#//NavigationClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="BinaryClassAttribute" lowerBound="1"
        upperBound="-1" eType="#//BinaryAttribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DAOInterface" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Interface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="OwnBaseOperation" lowerBound="4"
        upperBound="4" eType="#//DAOBaseOperation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="OwnOperation" upperBound="-1"
        eType="#//DAOOperation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DAOInterfaceName" lowerBound="1"
        eType="#//DAOInterfaceName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DAOInterfaceAttribute"
        upperBound="-1" eType="#//DAOAttribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DAOClass" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class">
    <eStructuralFeatures xsi:type="ecore:EReference" name="BaseImplements" lowerBound="4"
        upperBound="4" eType="#//DAOBaseOperation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DAOImplements" upperBound="-1"
        eType="#//DAOOperation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DAOClassName" lowerBound="1"
        eType="#//DAOClassName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DAOClassAttribute" upperBound="-1"
        eType="#//DAOAttribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DAOGeneralization" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Generalization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="TargetDAOClass" lowerBound="1"
        eType="#//DAOClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SourceDAOInterface" lowerBound="1"
        eType="#//DAOInterface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FrontControllerClass" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class">
    <eStructuralFeatures xsi:type="ecore:EReference" name="FrontControllerAttribute"
        lowerBound="1" upperBound="-1" eType="#//IOParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FrontControllerClassMethod"
        lowerBound="1" upperBound="-1" eType="#//FrontControllerMethod" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserViewAttribute" eSuperTypes="#//NavigationAttribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="IOParameter" eSuperTypes="#//NavigationAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="display" upperBound="-1"
        eType="#//FormComponent" derived="true" eOpposite="#//FormComponent/inject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DAOBaseOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DAObaseOperationName" eType="#//DAOBaseOperationList"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DAOBaseOperationList">
    <eLiterals name="retrieve"/>
    <eLiterals name="retrieveAll" value="1"/>
    <eLiterals name="save" value="2"/>
    <eLiterals name="delete" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FrameworkCategoryList">
    <eLiterals name="MVC" literal="mvc"/>
    <eLiterals name="DependencyInjection" value="1"/>
    <eLiterals name="ORM" value="2"/>
    <eLiterals name="Decorator" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResultDependency" eSuperTypes="#//NavigationDependency">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ReturnResult" upperBound="-1"
        eType="#//Result"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ReturnMethod" lowerBound="1"
        eType="#//FrontControllerMethod"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SourceFrontController"
        lowerBound="1" eType="#//FrontControllerClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TargetTemplate" eType="#//Template"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TargetPage" eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TargetBinary" eType="#//Binary"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ReturnResultType" upperBound="-1"
        eType="#//ResultType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TargetForm" eType="#//Form"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TargetComponent" eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TargetJQuery" eType="#//JQuery"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TargetFormComponent" eType="#//FormComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationComposition" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Association">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SourceTemplate" eType="#//Template"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SourcePage" eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TargetForm" lowerBound="1"
        eType="#//Form"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TargetComponent" lowerBound="1"
        eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TargetJQuery" lowerBound="1"
        eType="#//JQuery"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FrontControllerMethod" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDefault" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamingMethod" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Contains" lowerBound="1"
        upperBound="-1" eType="#//SFrameWebName" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceClass" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ServiceClassAttribute"
        eType="#//ServiceAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ServiceClassOperation"
        upperBound="-1" eType="#//ServiceOperation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceInterface" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Interface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ServiceInterfaceOperation"
        upperBound="-1" eType="#//ServiceOperation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ServiceInterfaceAttribute"
        upperBound="-1" eType="#//ServiceAttribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceGeneralization" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Generalization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SourceServiceInterface"
        lowerBound="1" eType="#//ServiceInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TargetServiceClass" lowerBound="1"
        eType="#//ServiceClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceNavigationAssociation" eSuperTypes="#//ServiceAssociation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SourceServiceClass" lowerBound="1"
        eType="#//ServiceInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TargetFrontController"
        lowerBound="1" eType="#//FrontControllerClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainClass" abstract="true" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class">
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainClassAttribute" lowerBound="1"
        upperBound="-1" eType="#//DomainAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainClassOperation" upperBound="-1"
        eType="#//DomainOperation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SFrameWebName" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryAttribute" eSuperTypes="#//NavigationAttribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantName" eSuperTypes="#//SFrameWebName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fwName" eType="#//ConstantNameList"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainTableName" eSuperTypes="#//SFrameWebName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fwName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PersistentClassName" lowerBound="1"
        eType="#//PersistentClass" eOpposite="#//PersistentClass/Table"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FrameWorkName" eSuperTypes="#//SFrameWebName"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ConstantNameList">
    <eLiterals name="DAO"/>
    <eLiterals name="interface" value="1"/>
    <eLiterals name="base" value="2"/>
    <eLiterals name="class" value="3"/>
    <eLiterals name="impl" value="4"/>
    <eLiterals name="Controller" literal="Controller"/>
    <eLiterals name="Domain"/>
    <eLiterals name="Persistence" literal="Persistence"/>
    <eLiterals name="Application"/>
    <eLiterals name="View"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainColumnName" eSuperTypes="#//SFrameWebName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fwName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainAttributeName" lowerBound="1"
        eType="#//DomainAttribute" eOpposite="#//DomainAttribute/Column"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DAOInterfaceName" eSuperTypes="#//ConstantName">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConstantPrefix" eType="#//ConstantName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainTablePrefix" eType="#//DomainTableName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DAOClassName" eSuperTypes="#//DAOInterfaceName">
    <eStructuralFeatures xsi:type="ecore:EReference" name="FrameWorkNameSufix" lowerBound="1"
        eType="#//FrameWorkName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Result"/>
  <eClassifiers xsi:type="ecore:EClass" name="FrontControllerDependency" eSuperTypes="#//NavigationDependency">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Method" lowerBound="1"
        eType="#//FrontControllerMethod"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SourceForm" eType="#//Form"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TargetFrontController"
        lowerBound="1" eType="#//FrontControllerClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SourcePage" eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SourceTemplate" eType="#//Template"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SourceComponent" eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SourceJQuery" eType="#//JQuery"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PageDependency" eSuperTypes="#//NavigationDependency">
    <eStructuralFeatures xsi:type="ecore:EReference" name="TargetPage" lowerBound="1"
        eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SourceTemplate" eType="#//Template"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linkHTML" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SourcePage" eType="#//Page"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChainingDependency" eSuperTypes="#//NavigationDependency">
    <eStructuralFeatures xsi:type="ecore:EReference" name="OutMethod" lowerBound="1"
        eType="#//FrontControllerMethod"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="InMethod" lowerBound="1"
        eType="#//FrontControllerMethod"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TargetFrontController"
        lowerBound="1" eType="#//FrontControllerClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SourceFrontController"
        lowerBound="1" eType="#//FrontControllerClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DAOServiceAssociation" eSuperTypes="#//ServiceAssociation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SourceDAOClass" lowerBound="1"
        eType="#//DAOInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TargetDAOService" lowerBound="1"
        eType="#//ServiceClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationAttribute" abstract="true"
      eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
  <eClassifiers xsi:type="ecore:EEnum" name="InheritanceMapping">
    <eLiterals name="singletable"/>
    <eLiterals name="union" value="1"/>
    <eLiterals name="join" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationClass" abstract="true" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainOperation" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="DAOAttribute" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceOperation" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceAttribute" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceAssociation" abstract="true"
      eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Association"/>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationDependency" abstract="true"
      eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Dependency"/>
  <eClassifiers xsi:type="ecore:EClass" name="DAOOperation" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainPackage" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainPackageClass" lowerBound="1"
        upperBound="-1" eType="#//DomainClass" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewPackage" eSuperTypes="#//NavigationPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ViewPackageClass" lowerBound="1"
        upperBound="-1" eType="#//NavigationClass" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControllerPackage" eSuperTypes="#//NavigationPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ControllerPackageClass"
        lowerBound="1" upperBound="-1" eType="#//FrontControllerClass" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersistencePackage" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package">
    <eStructuralFeatures xsi:type="ecore:EReference" name="PersistencePackageInterface"
        lowerBound="1" upperBound="-1" eType="#//DAOInterface" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PersistencePackageClass"
        lowerBound="1" upperBound="-1" eType="#//DAOClass" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationPackage" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ServicePackageClass" lowerBound="1"
        upperBound="-1" eType="#//ServiceClass" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ServicePackageInterface"
        lowerBound="1" upperBound="-1" eType="#//ServiceInterface" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//NavigationClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResultType"/>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationPackage" abstract="true" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainGeneralization" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Generalization">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapping" eType="#//InheritanceMapping"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TargetDomain" lowerBound="1"
        eType="#//DomainClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SourceDomain" lowerBound="1"
        eType="#//DomainClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JQuery" eSuperTypes="#//NavigationClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="FormComponent" instanceTypeName="FrameworkTag"
      eSuperTypes="#//NavigationAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inject" eType="#//IOParameter"
        eOpposite="#//IOParameter/display"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TagLib" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package">
    <eStructuralFeatures xsi:type="ecore:EReference" name="TagLibTag" lowerBound="1"
        upperBound="-1" eType="#//FrameworkTag" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FrameworkTag" eSuperTypes="#//Tag"/>
  <eClassifiers xsi:type="ecore:EClass" name="Rule"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tag" abstract="true" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SubTag" upperBound="-1"
        eType="#//Tag" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Anotation"/>
</ecore:EPackage>
